name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Notify Discord of build start
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "embeds": [
              {
                "title": "🔨 Build Process Started",
                "description": "The build process has started for commit **${{ github.sha }}**.",
                "color": 5814783,
                "fields": [
                  {
                    "name": "Branch",
                    "value": "${{ github.ref }}",
                    "inline": true
                  },
                  {
                    "name": "Commit",
                    "value": "[${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})",
                    "inline": true
                  }
                ],
                "footer": {
                  "text": "Marom Medical CI/CD"
                }
              }
            ]
          }' ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            abdulrhmanashraf98/marom-medical:${{ github.sha }}
            abdulrhmanashraf98/marom-medical:latest
          build-args: |
            APP_PORT=${{ secrets.APP_PORT }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            DB_TYPE=${{ secrets.DB_TYPE }}

      - name: Run tests
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app abdulrhmanashraf98/marom-medical:${{ github.sha }} npm test
        continue-on-error: true

      - name: Notify Discord of test failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "embeds": [
              {
                "title": "❌ Build Process Failed",
                "description": "The build process failed for commit **${{ github.sha }}**.",
                "color": 15548997,
                "fields": [
                  {
                    "name": "Branch",
                    "value": "${{ github.ref }}",
                    "inline": true
                  },
                  {
                    "name": "Commit",
                    "value": "[${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})",
                    "inline": true
                  }
                ],
                "footer": {
                  "text": "Marom Medical CI/CD"
                }
              }
            ]
          }' ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Deploy to EC2
        if: success()
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull abdulrhmanashraf98/marom-medical:${{ github.sha }}
            docker pull abdulrhmanashraf98/marom-medical:latest
            docker stop your-container || true
            docker rm your-container || true
            docker run -d --name your-container -p 80:80 abdulrhmanashraf98/marom-medical:${{ github.sha }}
        continue-on-error: true

      - name: Notify Discord of deployment failure
        if: failure() && steps.build.outcome == 'success'
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "embeds": [
              {
                "title": "❌ Deployment Failed",
                "description": "Deployment failed for commit **${{ github.sha }}**.",
                "color": 15548997,
                "fields": [
                  {
                    "name": "Branch",
                    "value": "${{ github.ref }}",
                    "inline": true
                  },
                  {
                    "name": "Commit",
                    "value": "[${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})",
                    "inline": true
                  }
                ],
                "footer": {
                  "text": "Marom Medical CI/CD"
                }
              }
            ]
          }' ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Discord of build completion
        if: success()
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "embeds": [
              {
                "title": "✅ Build Process Completed",
                "description": "Build process completed successfully for commit **${{ github.sha }}**.",
                "color": 3066993,
                "fields": [
                  {
                    "name": "Branch",
                    "value": "${{ github.ref }}",
                    "inline": true
                  },
                  {
                    "name": "Commit",
                    "value": "[${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})",
                    "inline": true
                  }
                ],
                "footer": {
                  "text": "Marom Medical CI/CD"
                }
              }
            ]
          }' ${{ secrets.DISCORD_WEBHOOK_URL }}
