name: Test and Build

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Notify Discord of test start
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "embeds": [{
              "title": "🛠️ Test Started",
              "description": "Running tests for commit `${{ github.sha }}`.",
              "color": 16776960,
              "thumbnail": {
                "url": "https://example.com/start-image.png"
              },
              "fields": [
                {
                  "name": "Commit SHA",
                  "value": "${{ github.sha }}",
                  "inline": true
                }
              ],
              "footer": {
                "text": "GitHub Actions CI/CD"
              }
            }]
          }' ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Run tests
        id: test
        run: npm test
        continue-on-error: true

      - name: Notify Discord of test result
        if: always()
        run: |
          if [ "${{ steps.test.outcome }}" == 'failure' ]; then
            TEST_LOG=$(tail -n 10 /path/to/test/log || echo "No test log available.")
            curl -H "Content-Type: application/json" -X POST -d '{
              "embeds": [{
                "title": "❌ Test Failure",
                "description": "Tests failed for commit `${{ github.sha }}`. Check the logs for details.",
                "color": 16711680,
                "thumbnail": {
                  "url": "https://example.com/failure-image.png"
                },
                "fields": [
                  {
                    "name": "Commit SHA",
                    "value": "${{ github.sha }}",
                    "inline": true
                  },
                  {
                    "name": "Error Log",
                    "value": "```${TEST_LOG}```"
                  }
                ],
                "footer": {
                  "text": "GitHub Actions CI/CD"
                }
              }]
            }' ${{ secrets.DISCORD_WEBHOOK_URL }}
            exit 1
          else
            curl -H "Content-Type: application/json" -X POST -d '{
              "embeds": [{
                "title": "✅ Test Success",
                "description": "Tests passed for commit `${{ github.sha }}`.",
                "color": 65280,
                "thumbnail": {
                  "url": "https://example.com/success-image.png"
                },
                "fields": [
                  {
                    "name": "Commit SHA",
                    "value": "${{ github.sha }}",
                    "inline": true
                  }
                ],
                "footer": {
                  "text": "GitHub Actions CI/CD"
                }
              }]
            }' ${{ secrets.DISCORD_WEBHOOK_URL }}
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Notify Discord of build start
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "embeds": [{
              "title": "🔨 Build Started",
              "description": "Build process started for commit `${{ github.sha }}`.",
              "color": 16776960,
              "thumbnail": {
                "url": "https://example.com/start-image.png"
              },
              "fields": [
                {
                  "name": "Commit SHA",
                  "value": "${{ github.sha }}",
                  "inline": true
                }
              ],
              "footer": {
                "text": "GitHub Actions CI/CD"
              }
            }]
          }' ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Build Docker image
        id: build
        run: |
          docker buildx build \
            --build-arg APP_PORT=${{ secrets.APP_PORT }} \
            --build-arg DB_HOST=${{ secrets.DB_HOST }} \
            --build-arg DB_PORT=${{ secrets.DB_PORT }} \
            --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --build-arg DB_DATABASE=${{ secrets.DB_DATABASE }} \
            --build-arg DB_TYPE=${{ secrets.DB_TYPE }} \
            --build-arg DB_DATABASE_SYNCHRONIZE=${{ secrets.DB_DATABASE_SYNCHRONIZE }} \
            -t abdulrhmanashraf98/marom-medical:${{ github.sha }} \
            -t abdulrhmanashraf98/marom-medical:latest \
            --push \
            . > build.log 2>&1 || (echo "Docker build failed" && cat build.log && exit 1)

      - name: Notify Discord of build result
        if: always()
        run: |
          if [ "${{ steps.build.outcome }}" == 'success' ]; then
            curl -H "Content-Type: application/json" -X POST -d '{
              "embeds": [{
                "title": "✅ Build Success",
                "description": "Build completed successfully for commit `${{ github.sha }}`.",
                "color": 65280,
                "thumbnail": {
                  "url": "https://example.com/success-image.png"
                },
                "fields": [
                  {
                    "name": "Commit SHA",
                    "value": "${{ github.sha }}",
                    "inline": true
                  }
                ],
                "footer": {
                  "text": "GitHub Actions CI/CD"
                }
              }]
            }' ${{ secrets.DISCORD_WEBHOOK_URL }}
          else
            BUILD_LOG=$(tail -n 10 build.log || echo "No build log available.")
            curl -H "Content-Type: application/json" -X POST -d '{
              "embeds": [{
                "title": "❌ Build Failure",
                "description": "Build failed for commit `${{ github.sha }}`. Check the logs for details.",
                "color": 16711680,
                "thumbnail": {
                  "url": "https://example.com/failure-image.png"
                },
                "fields": [
                  {
                    "name": "Commit SHA",
                    "value": "${{ github.sha }}",
                    "inline": true
                  },
                  {
                    "name": "Error Log",
                    "value": "```${BUILD_LOG}```"
                  }
                ],
                "footer": {
                  "text": "GitHub Actions CI/CD"
                }
              }]
            }' ${{ secrets.DISCORD_WEBHOOK_URL }}
            exit 1
          fi
